# Basic Config
local|dotfiles/tmux.conf|.tmux.conf
local|dotfiles/gitconfig|.gitconfig
local|dotfiles/condarc|.condarc
local|dotfiles/sxhkd/sxhkdrc|.config/sxhkd/sxhkdrc
local|dotfiles/pip.conf|.config/pip/pip.conf
local|dotfiles/dunst/dunstrc|.config/dunst/dunstrc
local|dotfiles/rofi/config.rasi|.config/rofi/config.rasi
local|dotfiles/ssh-config|.ssh/config
local|dotfiles/pics/wall|.local/share/pics/wallpaper
local|dotfiles/xdg-desktop-portal-wlr/config|.config/xdg-desktop-portal-wlr/config
local|dotfiles/alacritty/alacritty.toml|.config/alacritty.toml
local|dotfiles/icons_default/index.theme|.local/share/icons/default/index.theme

# GTK
local|dotfiles/gtk-3.0/settings.ini|.config/gtk-3.0/settings.ini
local|dotfiles/gtk-4.0/settings.ini|.config/gtk-4.0/settings.ini

# Zsh
local|dotfiles/zsh/zshrc|.zshrc
local|dotfiles/zsh/zprofile|.zprofile
remote|https://github.com/zsh-users/zsh-autosuggestions.git|.zsh-scripts/zsh-autosuggestions
remote|https://github.com/zsh-users/zsh-syntax-highlighting.git|.zsh-scripts/zsh-syntax-highlighting
remote|https://github.com/zsh-users/zsh-history-substring-search.git|.zsh-scripts/zsh-history-substring-search

# Neovim
remote|https://github.com/novel2430/nvim.git|.config/nvim

# Wezterm
remote|https://github.com/novel2430/wezterm-config.git|.config/wezterm

# DWL
local|dotfiles/dwl/waybar.css|.config/dwl/waybar.css
local|dotfiles/dwl/waybar.jsonc|.config/dwl/waybar.jsonc

# DWM
local|dotfiles/dwm-autostart.sh|.dwm/autostart.sh

# Wayfire
local|dotfiles/wayfire/wayfire.ini|.config/wayfire.ini
local|dotfiles/wayfire/waybar.css|.config/wayfire/waybar.css
local|dotfiles/wayfire/waybar.jsonc|.config/wayfire/waybar.jsonc
