[window]
padding = { x = 5, y = 5 }
opacity = 0.9
decorations = "None"

[scrolling]
history = 50000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 14

[colors.primary]
foreground = "#eceff4"
background = "#2d2825"

[colors.normal]
black = '#3b4252'
red = '#bf616a'
green = '#a3be8c'
yellow = '#ebcb8b'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#88c0d0'
white = '#e5e9f0'

[colors.bright]
black = '#465780'
red = '#d06f79'
green = '#b1d196'
yellow = '#f0d399'
blue = '#8cafd2'
magenta = '#c895bf'
cyan = '#93ccdc'
white = '#e7ecf4'
