xrdb ~/.Xresources

export XCURSOR_THEME="Bibata-Modern-Classic"
export XCURSOR_SIZE="24"
export XCURSOR_PATH="$HOME/.local/share/icons:$HOME/.icons:/usr/local/share/icons:/usr/share/icons:/usr/share/pixmaps"

# exec dbus-run-session openbox-session
# exec dbus-run-session awesome
exec dbus-launch --exit-with-session dwm
# exec dbus-run-session /home/novel2430/src/dwm/dwm
